import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import AuthGuard from "./components/auth/AuthGuard";
import Footer from "./components/Footer";
import { AuthProvider } from "@front/context/AuthContext";
import NavMenu from "./components/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" data-theme="abricot">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Input toggle doit être directement sous body */}

        <AuthProvider>
          <div className="drawer drawer-mobile h-full">
            <input
              id="drawer-toggle"
              type="checkbox"
              className="drawer-toggle"
            />
            <div className="drawer-content flex flex-col">
              <Header />
              <AuthGuard>
                <main className="flex-1 p-4">{children}</main>
              </AuthGuard>
              <Footer />
            </div>

            <div className="drawer-side">
              <label htmlFor="drawer-toggle" className="drawer-overlay"></label>
              <div className="p-4 w-64 h-full bg-base-200 text-base-content">
                <NavMenu vertical />
              </div>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
